// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace CMS.Domain.Entities
{
    [Table(nameof(AuditLog))]
    public partial class AuditLog
    {
        public Guid Id { get; set; }
        public short ActionCategory { get; set; }
        public short Action { get; set; }
        public Guid UserId { get; set; }
        public string UserAddress { get; set; }
        public DateTime OccuredOn { get; set; }

        [NotMapped]
        public virtual User User { get; set; }
    }
}