// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using System;

namespace CMS.Domain.Entities
{
    public partial class CMSContext
    {

        [DbFunction("fn_GetVersion", "dbo")]
        public static string fn_GetVersion()
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }
    }
}
