// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace CMS.Domain.Entities
{
    public partial class User
    {
        public User()
        {
            AuditLogs = new HashSet<AuditLog>();
            EntryCreatedByNavigations = new HashSet<Entry>();
            EntryLastUpdatedByNavigations = new HashSet<Entry>();
            SectionCreatedByNavigations = new HashSet<Section>();
            SectionLastUpdatedByNavigations = new HashSet<Section>();
        }

        public Guid Id { get; set; }
        public string Email { get; set; }
        public byte[] Password { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public bool IsAdmin { get; set; }
        public DateTime CreatedOn { get; set; }
        public Guid CreatedBy { get; set; }
        public DateTime LastUpdatedOn { get; set; }
        public Guid LastUpdatedBy { get; set; }

        public virtual ICollection<AuditLog> AuditLogs { get; set; }
        public virtual ICollection<Entry> EntryCreatedByNavigations { get; set; }
        public virtual ICollection<Entry> EntryLastUpdatedByNavigations { get; set; }
        public virtual ICollection<Section> SectionCreatedByNavigations { get; set; }
        public virtual ICollection<Section> SectionLastUpdatedByNavigations { get; set; }
    }
}