name: Master - Build, Test, Pack & Publish

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Clean
      run: dotnet clean ./CMS.Domain.sln -- configuration Release && dotnet nuget locals all --clear
    - name: Restore dependencies
      run: dotnet restore
    - name: Build (Debug)
      run: dotnet build --no-restore
    - name: Test
      run: |
        dotnet test --no-build Tests/CMS.Domain.Tests/CMS.Domain.Tests.csproj --verbosity normal /p:CollectCoverage=true /p:CoverletOutput=${{ github.workspace }}/coverage/
        dotnet test --no-build Tests/CMS.Domain.Repositories.Tests/CMS.Domain.Repositories.Tests.csproj --verbosity normal /p:CollectCoverage=true /p:CoverletOutput=${{ github.workspace }}/coverage/ /p:MergeWith=${{ github.workspace }}/coverage
    - name: List
      run: ls -la ${{ github.workspace }}/Coverage
    - name: Publish Coverage
      uses: codacy/codacy-coverage-reporter-action@0.2.0
      with:
        project-token: ${{ secrets.CODACY_TOKEN }}
        coverage-reports: coverage.json
    - name: Build (Release)
      run: dotnet build -c Release --no-restore
    - name: Pack
      run: nuget pack ./CMS.Domain.All/.nuspec -OutputDirectory ./dist/ -Prop Configuration=Release -Suffix CI-${GITHUB_RUN_NUMBER}
    - name: Publish
      run: dotnet nuget push ./dist/*nupkg -s https://nuget.pkg.github.com/AdamBOD/index.json --api-key="${{ secrets.GPR_TOKEN }}"
